### PR TITLE
feat: add instagram, mastodon, linkedin, bluesky and github socials for community and users, and make social navbar configurable

### LINKED ISSUE #2514: Add Mastodon profile to Community settings (and, thus, to Header & Footer social media sections)
### Discussed in https://github.com/pubpub/pubpub/discussions/2513

<div type='discussions-op-text'>

<sup>Originally posted by **tosteiner** February  7, 2023</sup>
With the increasing popularity of Mastodon as the major Fediverse alternative to Twitter, I was wondering if it would be possible to have a dedicated Mastodon line in the community settings, which would then auto-populate to Header and Footer areas in a similar way to what we currently have for Twitter?

In addition to that, if this could be rendered with the HTML `rel`-tag intact, this would help with direct integration with Mastodon's profile [link verification](https://docs.joinmastodon.org/user/profile/#verification) feature.

Screenshot of the area I'm referring to [here](https://cloud.flavoursofopen.science/index.php/s/MQDQWjgC5XNnecM).</div>

### PR DESCRIPTION
**Pull request by tefkah**
## Issue(s) Resolved

Closes #2514 
Closes #2513 

## Test Plan

1. Go to `/dash/settings/details`
2. Add an instagram and mastodon profile
3. Check that they show up in the footer and navbar
4. Check that they resolve to the proper page
5. For mastodon, check that it has the `rel="me"` attribute. This is used to verify that your domain belongs to you on mastodon

### Updated
1. go to `jtrialerror` community
2. click every link in the social navbar
3. Check that they go to a valid profile
4. go to `/user/profile/thomas-jorna`
5. click every link in that navbar
6. check that they go to a valid profile
7. Go to /dash/settings
8. Change the "These links will appear in your Community's " setting to "header only."
9. Save
10. Check that on `/` the socials no longer appear in the footer
11. Change it to "footer only"
12. Check that on `/` the socials no longer appear in the header
13. Change it back to `both`
14. Make screen width < 700px
15. Observe that social header dissapears even if setting is "header" or "both"

## Screenshots (if applicable)

New config
image

### Notes/Context/Gotchas

> [!WARNING]
> Migration needs to be run on prod for this to work

> [!NOTE]
> I hid the social navbar menu on mobile view, as it became almost impossible to see the normal navbar if all social items were set.
> I think it somewhat unnecessary to have the socials in the upper navbar, takes up too much space and is already available in the footer. 

Header only setting is maybe a bit redundant, as probably no one is going to set it to that as it will be hidden in mobile view.

### Possible follow ups

1. [x] Also add insta/mastodon to profile pages
3. [x] Replace facebook icon with newer one (the round one, the square one is outdated)
5. Replace twitter logo/name with X (bleh)

### CODE REVIEW

**Review by gabestein — APPROVED** [review]
Looks great. Thanks very much for this. Folks will be quite happy.

If you have the energy for a fast-follow, we also got a bluesky and linkedin request recently.

**Review by gabestein — APPROVED** [review]

**Comment by gabestein** [comment]
Thanks! Can I ask you for one more annoying follow-up here? Change the svg/logo we use for twitter to an svg for X?

**Comment by tefkah** [comment]
> Thanks! Can I ask you for one more annoying follow-up here? Change the svg/logo we use for twitter to an svg for X?

I can do it, even though in my heart it's still twitter 💔

I'll also change the labels on the settings pages to reflect that then (maybe i'll do `X (Twitter)`), although i'll leave the internal properties as `twitter`.

**Review by gabestein — APPROVED** [review]
Many thanks. LGTM!

**Pull request merged**
