### PR TITLE
fix: Make Editor read-only until Firebase finishes connecting

### LINKED ISSUE #1753: Refreshing the page can cause lost work
### What went wrong, step-by-step?
1. The editor had an issue connecting; a small yellow "Connecting..." message was displayed where there is usually green "Connected"
2. I assumed this was an innocuous bug, and no problem. I worked in an open tab for several days
3. While editing I pressed Ctrl+R with the intention of "redo"-ing a change I had "undo"-ed with Ctrl-Z, causing the page to refresh.
4. My work was lost
...

### What did you expect to happen?

Ideally in a situation like this, the contents of the edit buffer should have been cached locally and taken precedence over the copy stored on the server so that my work would not be lost.

### What browser/operating system were you using?

===

### PR DESCRIPTION
**Pull request by idreyn**
Resolves #1753

We've had a few reports of folks losing their work because `Editor` lets them add content in a stalled `connecting` state. This change makes the editor read-only until `status = 'connected'`. I've done a little work moving the responsibility for monitoring the connection around, and a little type-safety/cosmetic overhaul.

_Test plan:_

Check that:
- The editor works and persists your changes after refreshing
- You cannot type while the status bar says "Connecting..." (maybe try throttling your connection here)
- The collab-status indicator works as expected: `connecting -> connected -> (saving <-> saved) -> disconnected`

### CODE REVIEW

**Comment by howebenhowe** [comment]
I _think_ this is failing the testing instructions. When toggled to slow 3G speed, I was able to type in the editor while the indicator status still read `connecting` and then those edits were erased once the editor hopped to `connected`.
See screenshots:
Screenshot from 2022-01-25 11-37-21
Screenshot from 2022-01-25 11-39-24

**Review by howebenhowe — APPROVED** [review]
The code looks clean but my grasp on firebase is nascent at best. I have been lucky thus far. It does mean a firebase-savvy individual might want to pass eyes over this one.

**Comment by gabestein** [comment]
Was closing out some tickets and found the one that spurned this PR. So, bumping it to see if we can get it across the finish line.

**Review by 3mcd — APPROVED** [review]

**Comment by idreyn** [comment]
Good catch @howebenhowe, I fixed it now!

**Pull request merged**
